### ISSUE TITLE
OS Media Controls

### ISSUE THREAD

**Issue by s-maurice** [Spotifyd/spotifyd#1032]
**Is your feature request related to a problem? Please describe.**
I was wondering if it is in scope for spotifyd to link with os media controls. Should the link to OS media controls be handled by implementing applications instead? (spotify-tui, etc.)

Perhaps this feature is already implemented but is not working for me? I'm on MacOS.

**Describe the solution you'd like**
Being able to use the media controls to play/pause/skip tracks.

**Describe alternatives you've considered**
I can see one rust crate ([souvlaki](https://docs.rs/souvlaki/latest/souvlaki/)) providing cross-platform handling but it seems pretty new.

**Comment by eladyn** [comment]
Hi!

`spotifyd` does already implement the MPRIS Spec (more or less) for Linux Media Controls (see [here](https://github.com/Spotifyd/spotifyd/blob/603bcc4d802d2b8f45ac517c0513eb4096252d7b/src/dbus_mpris.rs) or [here](https://github.com/Spotifyd/spotifyd/blob/603bcc4d802d2b8f45ac517c0513eb4096252d7b/Cargo.toml#L53)). I don't know of any implementation for MacOS or Windows.

The crate you mentioned does look interesting, but AFAICT it would only work on MacOS and Linux since Windows requires a some Window to be open. But still, the MacOS implementation for the controls [doesn't seem to be easy](https://github.com/Sinono3/souvlaki/blob/484d22c5b7e6a0a3ce5a534464a4c9d971b1b32e/src/platform/macos/mod.rs), so leveraging it for this matter might be a good idea.

*(Just my two cents, since I'm not a maintainer of this project...)*

**Comment by s-maurice** [comment]
So I've had a play around and it seems that MacOS also requires a window to be open.

**Comment by eladyn** [comment]
Oh, that's a pity. I just found [this issue](https://github.com/hrkfdn/ncspot/issues/519) from ncspot, which seems to be about the same thing and it might be interesting to follow what they come up with.
