### ISSUE TITLE
limit cache size config

### ISSUE THREAD

**Issue by trisbele** [Spotifyd/spotifyd#1066]
Thanks for spotifyd. I have to clear my cache manually every two weeks, because the cache on my raspberry2 is full and the daemon — and of coarse other processes as well — stucks and doesn't play any songs.
Limit  the maximum cache size possibility in config file would be nice.
Delete the oldest when max size is reached would be the smartest way, if it is easy to implement. But clear cache completely is also a valid solution for me and the easiest way....
THX

**Comment by eladyn** [comment]
To fix your specific problem, I guess you could disable caching completely (by omitting the `cache_directory` from your config file). If you don't need any of the features that spotifyd provides on top of `librespot` you could also [use the upstream project directly](https://github.com/librespot-org/librespot#quick-start) and use their `--cache-size-limit` cli option.

---

For anyone looking to implement this: `librespot` (the upstream dependency that spotifyd uses) allows to specify a max cache size and spotifyd could make use of that in this line:

https://github.com/Spotifyd/spotifyd/blob/f8fce08b4f81397d5628f40d9379e93ff7bbe073/src/config.rs#L591

which would need to be replaced by a proper value instead of `None`.
