### ISSUE TITLE
Mono playback

### ISSUE THREAD

**Issue by splitti** [Spotifyd/spotifyd#1076]
**Is your feature request related to a problem? Please describe.**
I tried to change the playback to mono. I use the Hifiberry Miniamp, just with one speaker. I tried a lot of settings in the asound.conf. Also in Pulseaudio, nothing worked to me.

**Describe the solution you'd like**
A parameter or config value to playback to just one speaker (all sound channels).

**Describe alternatives you've considered**
Tried to merge the channels in the asound.conf. But this isn't working.

**Comment by eladyn** [comment]
I'm not too experienced with audio setups, but I'm currently failing to understand your problem, sorry!

As far as I can see, you get at least some control over the audio playback with [those config options](https://github.com/Spotifyd/spotifyd/blob/ae6dac7a54f899316674ba57ce4a0f9890cd2b1c/src/config.rs#L329-L335) and should be able to select a single device via `device = "..."`.

Could you try to describe, how exactly you'd imagine such a configuration parameter and how it would influence the playback? Otherwise, I'd appreciate some pointers, where I could learn more about your specific setup. Maybe you could even try to make some other application (like `aplay`) do what you want and report, how you did it. That might make it easier for me (and potentially others, but maybe it's only me :smile: ) to understand your problem. Thanks!

**Comment by NNEU-1** [comment]
I think that what @splitti wants to do, is to mix left & right channels in order not to loose one channels audio information when listening over a single speaker.

However, this has absolutely nothing to do with Spotifyd - thus this issue should be closed.

**Comment by eladyn** [comment]
@splitti Feel free to add details what exactly you'd need, and I'll happily reopen this issue.
