### ISSUE TITLE
Dependabot status is broken

### ISSUE THREAD

**Issue by yadunandanbhat** [Spotifyd/spotifyd#1077]
see the below image
![image](https://user-images.githubusercontent.com/54680617/163363407-addaa5cb-006c-4c5e-82f6-1f3f197b92a5.png)

**Comment by eladyn** [comment]
Thanks for reporting. Apparently, dependabot stopped working for this repo, since the PR that would have upgraded to the new github-native dependabot (https://github.com/Spotifyd/spotifyd/pull/943) was closed as stale.

Apart from that, it seems that the old badge URL wouldn't work anymore anyway, so it should be safe to remove it. Feel free to create a PR for this!

**Comment by yadunandanbhat** [comment]
Okay then! I'll update it and open a pr!

**Comment by yadunandanbhat** [comment]
I've opened a pr, but it needs review

**Comment by eladyn** [comment]
The PR has now been merged. :tada:
