### ISSUE TITLE
is there any support socks5 proxy?

### ISSUE THREAD

**Issue by littlesum** [Spotifyd/spotifyd#1087]
config proxy = socks5://127.0.0.1/10808

not work

**Comment by eladyn** [comment]
`spotifyd` uses `librespot` as its main dependency, which – in turn – uses `hyper-proxy`, in order to provide its proxying feature. After skimming over the `hyper-proxy` code, it seems like they unfortunately only support standard `HTTP` proxies. Still, I am not entirely sure, and you might want to ask somewhere else.

This is however nothing that can be fixed on the `spotifyd` side. Hope, this answers your question!
