### ISSUE TITLE
playerctl issue "No players found"

### ISSUE THREAD

**Issue by PaoloRondot** [Spotifyd/spotifyd#1094]
Hi,

I installed playerctl because from what I've seen, it looks very helpful to control the music being played by spotifyd.

I guess it is a beginner issue, but I can't find an answer to my "No players found" issue after running `playerctl status`.
When I went through the different issues, I didn't really understand the answers.

Are there some precise instructions that I should execute after installing playerctl to get it work with spotifyd ?

Many thanks !

**Comment by eladyn** [comment]
Hi!

Controlling spotifyd from playerctl should be possible with the following steps:

1. download a binary of this program with all features enabled (or at least `dbus_mpris`) or compile it yourself
2. configure and run spotifyd
3. start playing your music

After those steps, `playerctl status` should be working properly.

Hope this helps; if not, could you share the exact steps that you tried so that we can help you get further?

**Comment by PaoloRondot** [comment]
Hi!
Thanks for your answer. I think I'm missing the dbus_mpris part... could you get in further details ?

**Comment by eladyn** [comment]
Sure. You'll just need to download a "-full" version fron the releases, e.g. https://github.com/Spotifyd/spotifyd/releases/download/v0.3.3/spotifyd-linux-full.tar.gz . If you're on some architecture not listed there, you can compile the binary yourself. Instructions can be found [here](https://spotifyd.github.io/spotifyd/installation/index.html#building-from-source). At the compile step, add `--features "dbus_mpris"`.

Let me know, if this works for you!

**Comment by eladyn** [comment]
If there's something that's still not working for you, feel free to ping me and I'll reopen this issue!
