### ISSUE TITLE
Fashion

### ISSUE THREAD

**Issue by RobbieNelson** [Spotifyd/spotifyd#1134]
Fashion is a form of self-expression and autonomy at a particular period and place and in a specific context, of clothing, footwear, lifestyle, accessories, makeup, hairstyle, and body posture. The term implies a look defined by the fashion industry as that which is trending. Everything that is considered fashion is available and popularized by the fashion system (industry and media).

**Comment by CalRielder** [comment]
Fashion is one of the most important things for me because it helps to express my individuality. Anyway, I prefer buying accessories made from vegan leather as it looks better. So once I ran into resource where it was possible to buy [vegan briefcases](https://doshi.shop/collections/womens-vegan-briefcases-and-business-bags). This purchase is totally appropriate for me.
