### ISSUE TITLE
Wake speaker on playback

### ISSUE THREAD

**Issue by fritzfranzke** [Spotifyd/spotifyd#1136]
I have a speaker connected to both my desktop computer (S/PDIF) and my home server (audio jack). The latter runs `spotifyd`.
My speakers turn off after a certain time of inactivity. When I turn my PC on, the speakers wake up and I can play sound. However, my server does not wake the speakers when I play music using `spotifyd`. This requires me to turn them on manually. 

Ideally, the speakers wake up when I start palying music on the server.

Now I am not sure at which level this needs to be handled. Three options on who is responsible for waking the speakers come to mind:
* OS
* Audio backend (e.g. alsa)
* Application (i.e. spotifyd)

Maybe it turns out that there is no trivial solution. Unlike the desktop computer, the server is always on. Hence, sending a wake signal to the speakers when powering on would not solve the issue.

Thanks for your help!

**Comment by eladyn** [comment]
Hi!

I don't know much about such specific audio setups and thus can't help you with understanding what you need to change so that the speakers are turned on, when the server needs to play music. I would assume, though, that there isn't much that `spotifyd` itself can do. (If other players do work the intended way, this would be a different matter!)

I guess, you could try to use something different from ALSA and see if either `pulseaudio` or `pipewire` handle this in a better way. If you found out, what you need to do, we'll see, what `spotifyd` can do so that they're not always on, but only, when they're needed.

Hope you find something and feel free to report back, if you think that there's something that we could do in this project!

**Comment by NNEU-1** [comment]
Your question is slightly confusing, but if i understand correctly, your Spotifyd server is connected to the speakers using an analog "audio jack" (3.5mm phono ?).

In that case, it seems that your speakers don't have any analog signal detection on that input.
The S/PDIF input probably has carrier detection.

This issue is thus entirely unrelated to Spotifyd. Please close.

**Comment by eladyn** [comment]
@NNEU-1 thanks for clearing this up, that seems like a great explanation of what might be happening!

@fritzfranzke if you consider this still in scope for `spotifyd` for whatever reason, please report back and I'll reopen. :)

**Comment by fritzfranzke** [comment]
Hi, thanks for your insights! Please excuse my late reply :/ I tried setting up another media player to try your suggestion and see if other applications are successful in waking the speaker. However, I feel that the Linux audio stack can turn out to be quite he rabbithole, and so far I haven't had the time to really dive into it. IIRC I had the speakers connected to my desktop via 3.5mm phone jack and waking worked just fine, so I am guessing there must be some way to achieve this. Regardless, after all you said and what I managed to understand thus far I also doubt that `spotifyd` is the correct layer to adress this. 

Thanks for your awesome work! :)
