### ISSUE TITLE
System volume != Spotify volume

### ISSUE THREAD

**Issue by mbndr** [Spotifyd/spotifyd#115]
First of all, I really like this project, it's installed on my RPI and working very well! Searched a while for that :)

Currently I'm experimenting with volume control in a script to build a physical control for the volume (currently a xbox-controller because nothing else is available now). 
My problem is that the Spotify volume doesn't correspond to the system volume retrieved with `amixer`. If the Spotify volume is 0% the system's volume is 38%. I don't really know the difference between the `volume-control` settings (a small documentation entry for noobs as me would be great) and I'm not really into sound and alsa etc.
I'm using the RPI builtin soundcard, could this be the problem?

**Comment by SimonPersson** [comment]
Generally, the spotify volume will not correspond directly to what you read from `amixer`, because we increase the volume on a logarithmic scale, whereas amixer gives you the volume on a linear scale. On my system alsamixer more or less coresponds to the spotify volume, but amixer is way off. That sounds like a bug though, because 0% -> 38% should not be possible.

Unfortunately I don't have a Raspberry Pi so I can't debug this. Could you try the `alsa_linear` controller?
