### ISSUE TITLE
error when compiling

### ISSUE THREAD

**Issue by Jorpy76** [Spotifyd/spotifyd#1190]
Hi there : I have an error when compiling in Debian 11:

cargo 1.68.0 (115f34552 2023-02-26)
spotifyd 0.3.4

warning: unused imports: `error`, `warn`
  --> src/setup.rs:20:11
   |
20 | use log::{error, info, warn};
   |           ^^^^^        ^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

warning: `spotifyd` (bin "spotifyd") generated 1 warning
    Finished release [optimized] target(s) in 0.33s
warning: the following packages contain code that will be rejected by a future version of Rust: daemonize v0.4.1
note: to see what the problems were, use the option `--future-incompat-report`, or run `cargo report future-incompatibilities --id 2`

**Comment by eladyn** [comment]
Thank you for the report! The messages you're getting aren't actually errors, but warnings which shouldn't prevent you from successfully compiling `spotifyd`. Nonetheless, both are valid points! The first warning (unused imports) should be fixed by #1182 and the second by #1183 (assuming `daemonize 0.5` gets rid of that incompatible code).
