### ISSUE TITLE
Volume Controllers behave weirdly

### ISSUE THREAD

**Issue by Arbee4ever** [Spotifyd/spotifyd#1222]
**Description**
softvol: changes it just for spotify and properly from 0 to 100 (I think), but doesnt show these changes in system volume mixer
alsa: Sets 0 volume to be around 80% actual volume so its very loud when I try to increase the volume from my phone through spotify.
alsa_linear: Properly sets it from 0 to 100, but sets system volume and not just "spotifyd" and resets it to 0 everytime I pause and play
none: Doesnt let me change it from the phone

**To Reproduce**
1. Install spotifyd
2. try all different volume controllers

**Expected behavior**
All should show spotifyd's volume on a separate slider in mixer and properly set the volume from 0 to 100

**Logs**
I can't provide logs for all four controllers

**Versions (please complete the following information):**

- OS: Fedora 38
- Spotifyd: 0.3.5
- cargo: 1.72.0

**Comment by eladyn** [comment]
The behaviour you describe for `softvol` and `none` is entirely intended, since `softvol` is doing the volume adjustment within the software and not in the audio server and `none` is for when you don't want to use volume control at all.

Regarding the other two modes: Do you mean that setting the volume to 0 percent on the phone doesn't mute the audio, but causes `spotifyd` to play at 80% volume?

Regarding the system control vs. app volume control: We are using `alsa` for that and individual app volume controls are a feature that are specific to pulseaudio and other newer sound servers, AFAIK. So such a feature would require some implementation work.
And I would argue that if you're fine with Spotify's volume control only affecting `spotifyd`'s volume, you can just use `softvol`. (although then the volume doesn't get reported to the audio server, but you can still query and change it via the MPRIS interface, if needed)

Hope, that clears things up?

**Comment by ciembor** [comment]
I have problems with `alsa`, 0 is not 0, 100 is too loud. It works better with softvol in my case, but also not perfect (the characteristics of sound level change is probably not a common one).
