### ISSUE TITLE
Stats.fm compatability

### ISSUE THREAD

**Issue by gurv1r** [Spotifyd/spotifyd#1225]
**Is your feature request related to a problem? Please describe.**
A service called stats.fm lets users track their streams, but the functionality of it is missing when you use spotifyd.

**Describe the solution you'd like**
Compatibility Update

**Comment by eladyn** [comment]
Thank you for the report. I have no experience with stats.fm, so it would be great if you could describe in more detail, what is not working with `spotifyd´ and how it should work / works when using the official client.

In any case, I suspect that it might have something to do with https://github.com/librespot-org/librespot/discussions/626.

**Comment by BKasin** [comment]
It definitely seems to be the issue you linked. The desired behavior that you get with an official client is that every play gets counted on stats.fm to track your most played songs/artists/genres, as well as most recent plays. When using spotifyd (and I assume any other librespot based client), none of that data gets tracked.

For example, I'm currently using spotfiyd on my laptop but stats.fm shows my most recent plays as being when I was using my phone earlier today.

![stats](https://github.com/Spotifyd/spotifyd/assets/31324979/bae4a90d-ee4c-4f06-812e-d5eb1c8ec00f)

I'm guessing this will continue to be an issue until librespot is able to reverse engineer `event-service`, since it's suspected that that is how this data is tracked.
