### ISSUE TITLE
Zero conf authentication

### ISSUE THREAD

**Issue by kirk781** [Spotifyd/spotifyd#1240]
I setup spotifyd via zeroconf authentication method skipping username/password entries[as said on the site] in the config file. It showed up properly in the Spotify desktop app, however, I was trying to configure spotifyd to run with another app _spotify-qt_. The service still asks for authentication each time I fire up that client [and if I don't give the password, the spotifyd service that can be linked to start with the client says "password not provided"]. It doesn't detect any devices either. I tried inputting the password but still, the problem persists each time I restart the client. 

Shouldn't spotifyd just show up as an app option in the devices section instead of prompting for a password or does one needs to go back to the text based login method for it to work? Only that client and _spotify-tui_ are amongst the major ones that use this service as the backend. The latter seems to be deprecated now.

I just tried it with _spotify-tui_ as well but keep failing. This app gives other problems as well [due to non maintenance maybe] but I couldn't get spotifyd to detect here either. I must be doing something wrong. Is zeroconf authentication method more complicated than I initially thought?

Version: spotifyd 0.3.5
OS: Void Linux
Cargo : Since it was installed from the OS repos, no cargo install was used.

**Comment by eladyn** [comment]
I don't think, this is a problem with `spotifyd`. As long as it's working through the official client, the issue lies within `spotify-qt`.

Something that I'd like to say though, is that there aren't many Spotify clients apart from the official ones that support zeroconf discovery. (I don't know any.) So the way that you should be using it from within `spotify-qt` is login in `spotify-qt` and let `spotify-qt` take care of supplying your credentials to `spotifyd`.

Hope this helps.
