### ISSUE TITLE
Better handle alsa device disconnect/reconnect

### ISSUE THREAD

**Issue by archi** [Spotifyd/spotifyd#154]
Right now the daemon seems to dislike the audio device vanishing. Since I use a USB DAC, I can not avoid this (unless having the DAC running 24/7; which I would like to avoid).

Output (with the DAC plugged in during start):

```
[...]
21:45:06 [INFO] Track "Intergalactic Space Crusaders - Live" loaded
```
music is now playing, I turn of the device:

```
ALSA lib pcm_hw.c:1700:(_snd_pcm_hw_open) Invalid value for card
21:45:07 [ERROR] Alsa error PCM open -19
21:45:07 [ERROR] Could not start audio: Alsa error: PCM open failed
ALSA lib pcm_hw.c:1700:(_snd_pcm_hw_open) Invalid value for card
21:45:07 [ERROR] Alsa error PCM open -19
21:45:07 [ERROR] Could not start audio: Alsa error: PCM open failed
21:45:37 [ERROR] Caught panic with message: called `Result::unwrap()` on an `Err` value: -19
```

I try to play a song/turn the device back on:

```
21:46:05 [ERROR] Caught panic with message: called `Result::unwrap()` on an `Err` value: "SendError(..)"
21:46:05 [ERROR] Player thread panicked!
```

My device is set to `hw:CARD=x20,DEV=0`.

**Comment by pojebunny** [comment]
It's ALSAs issue, not spotifyd. It doesn't have support for conditional statements, so there is no way to pass audio from disconnected device to other and vice-versa (other than playing sound through both of them at the same time and just ignoring any disconnections)

**Comment by joshdurbin** [comment]
@archi my solution to this, which is not yet proven/executed on, but should work, is the following where spotifyd is stopped and started with the absence and presence of the USB dac. See [this](https://stackoverflow.com/questions/18463755/linux-start-daemon-on-connected-usb-serial-dongle) for more info.

1. Set a udev rule to monitor for the connection / disconnection (via power or otherwise physically removed)
2. Start/stop the systemd service that's running spotifyd

This means, however, that the Spotify target won't display unless the AMP/DAC is powered on.
