### ISSUE TITLE
Build time is a disaster

### ISSUE THREAD

**Issue by maikeldotuk** [Spotifyd/spotifyd#207]
I get it, Rust is amazing. I use it myself. Now the question is:
# Do you guys need to use every single Rust package that has been created since the Big-Bang?

For simple stuff such as adding mpris & pulseaudio support I have to forcefully go through compilation. We would all be terribly happy if you could offer a binary file including those two features at the same time. 

# 40 
## minutes 

...compilation time in a fairly recent and decent laptop it's...

## a 
# **crime**

..against humanity

**Comment by Mange** [comment]
Perhaps you could tone down the attitude a bit and suggest some alternatives or improvements on how to improve on this "crime against humanity" so the people working to please you *for free* can get something better.

**Comment by maikeldotuk** [comment]
Nothing is for free, either you write code for money or for wisdom at writing better code. Considering the later someone had to point out the elephant in the room. On 24 Feb 2019 14:43, Magnus Bergmark <notifications@github.com> wrote:Perhaps you could tone down the attitude a bit and suggest some alternatives or improvements on how to improve on this "crime against humanity" so the people working to please you for free can get something better.

**Comment by Mange** [comment]
And because someone writes something to gain wisdom, as you put it, you feel that it is proper to act entitled towards them?

**Comment by SimonPersson** [comment]
Hi! I'm sorry that Spotifyd is disappointing you. I think your frustration stems from this misunderstanding:

> Nothing is for free, either you write code for money or for wisdom at writing better code. 

Neither could be further from the truth, I hacked this project together for my own use, with little regard for code quality. I then shared it freely online, so that someone else could use it, either directly or as a starting point for their own project. I fix bugs and add features when I need them for my own use, or occasionally when I am bored.

Personally, I don't use mpris or pulseaudio. Given my rationale for building this project in the first place, I'm sure you can see why I have limited interest in improving those particular features.

Finally, I develop on an 8 year old computer. I have never seen build times that long. I'm sorry I can't be of more help, but something sounds strange about that.

**Comment by woftor** [comment]
> I get it, Rust is amazing. I use it myself. Now the question is:
> # Do you guys need to use every single Rust package that has been created since the Big-Bang?
> 
> For simple stuff such as adding mpris & pulseaudio support I have to forcefully go through compilation. We would all be terribly happy if you could offer a binary file including those two features at the same time.
> # 40
> ## minutes
> 
> ...compilation time in a fairly recent and decent laptop it's...
> ## a
> # **crime**
> 
> ..against humanity

What is wrong with you?
Seriously.

**Comment by SimonPersson** [comment]
I'm back at my computer to try this out. A clean build, launched with `time cargo build -j8 --release --no-default-features --features='pulseaudio_backend,dbus_mpris'`, takes 5 minutes and 42 seconds on my 8 year old desktop. I'll close this ticket.
