### ISSUE TITLE
ability to search for albums/playlists?

### ISSUE THREAD

**Issue by carnager** [Spotifyd/spotifyd#24]
does libspotify provide this feature? the official client can do it. result should be a single line, which - when added - will add all tracks associated with it, in correct order

**Comment by carnager** [comment]
oh wait. does sc search album:foo artist:bar do exactly what i want? it seems like it?

**Comment by SimonPersson** [comment]
You can kind of do this already. Something like `sc search "artist:\"Ramones\" album:\"Rocket to russia\""` gives you the album. Only problem is that it is not necessarily in album order.

**Comment by SimonPersson** [comment]
You beat me, yes, that works.

**Comment by carnager** [comment]
ok, in that case the request remains valid, since order is still an issue

**Comment by SimonPersson** [comment]
Yeah. I remember looking in to it but I think it got a bit nasty with a lot of callbacks and so on. Perhaps I will have to refactor some things first.

**Comment by SimonPersson** [comment]
So, @carnager, I just pushed this feature. Search results now get postfixes such as `| ALBUM` or `| TRACK` so that you can grep for whatever you are interested in. You add an album to the queue the same way you do with tracks.

However, I can't seem to find new playlists. I find those that I'm already following, but not new ones. Can you conform this? I'm wondering if I'm misunderstanding the Spotify API somehow, but from what I can see I'm doing the right things...

**Comment by SimonPersson** [comment]
@carnager: Another user spotted that I had a bug in the search code today. With my latest commit it is possible to search for playlists as well.
