### ISSUE TITLE
Noise in pipe

### ISSUE THREAD

**Issue by dflvunoooooo** [Spotifyd/spotifyd#256]
I get random noise in the pipe after a few tracks. Sometimes at the beginning of the second track, sometimes later.
I created a pipe with 
`mkfifo /tmp/snapfifo-Spotify`
and started spotifyd with 
`spotifyd --no-daemon --backend pipe > /tmp/snapfifo-Spotify`.
I than start the snapcast server, which streams the audio over the network. The same problem arises if I open the pipe with 
`aplay -c 2 -r 48000 -f S16_BE /tmp/snapfifo-Spotify` 
which was suggested here [https://github.com/Spotifyd/spotifyd/issues/198#issuecomment-467167159](url).
I have no idea why this happens. Can anybody help?
Everything works fine if I start spotfyd without the pipe option.

**Comment by SimonPersson** [comment]
I think the pipe backend is a bit broken currently. I guess that the pipe ends up containing both the log output, and the audio data? So the audio output only works for as long as the log output is an even number of bytes, otherwise audio samples will be shifted one byte, and you get noise :)

A solution would be to accept a `pipe_path` configuration option, where the audio output would go. I would be happy to accept a PR for such a change!

**Comment by Seshpenguin** [comment]
I'm having this same issue too. The first track will be fine, but when spotifyd starts playing the next track it is just noise.
I have it piped into ffmpeg.

**Comment by SirWindfield** [comment]
Could you guys elaborate a little bit more for me? I am not that familiar with pipes. How exactly does it work? Does it literally send the audio data into stdout?

**Comment by jgabriel98** [comment]
change the sample rate from 48000 to 44100
in other words:
> I than start the snapcast server, which streams the audio over the network. The same problem arises if I open the pipe with
`aplay -c 2 -r 48000 -f S16_BE /tmp/snapfifo-Spotify`

try to use `aplay -c 2 -r 44100 -f S16_BE /tmp/snapfifo-Spotify` instead. tell me if it solves the problem
