### ISSUE TITLE
Cannot connect on playlists with more than 2000 songs.

### ISSUE THREAD

**Issue by Birdroun** [Spotifyd/spotifyd#263]
Installed spotifyd using the rpi-audio-receiver script and got a small problem. There is no way to connect to a playlist with more than 2000 songs, using the desktop client or the android one. Is there a known problem, or is it on my side, can I help you to resolve it ?

**Comment by Birdroun** [comment]
Actually the problem might be more around 3000 songs.

**Comment by SirWindfield** [comment]
Looks more like a limitation of spotify if it's happening on the android and desktop client too.

Mind sharing your playlist? If I can load it then it's a problem on your side I guess.

The only thing that comes into my mind might be some poor programming on their side. A huge playlist of 1100 songs on Android would need 1100 instances of ListItems, one for each song. Normally, you cache and reuse them but since spotify is build on web technilogues they actually might just create that many nodes, which takes time and processing power, as well as a lot of RAM. I doubt that's the case but you never know.

**Comment by Birdroun** [comment]
Nah it's happening when trying to use connect, else it works perfectly on local !
And there some links for 3000k songs playlist that don't connect.
https://open.spotify.com/playlist/7zU5bQYEO4PUfEEhZdwnkf?si=pYAfgH--S8aeUGfGQ85Kkw
https://open.spotify.com/playlist/3XA30ma9IAZq4Nnm0UKGky?si=sD8BfU5xSViaE5V1PC6WxA
https://open.spotify.com/playlist/5nBkG5M8pDw5ZEcukZOXo9?si=IS4BwBYhThaIK8y8aGaK1A

I'm using a rpi2 for spotify connect if that can help !

**Comment by Birdroun** [comment]
This one with 2833 songs works
https://open.spotify.com/playlist/216DUR2BlUMIQqy32PrnXv?si=PkGY-nh5TuOc8OZYyKtGUQ

So it's around 3k that connect isn't working at all.

**Comment by SirWindfield** [comment]
So the last one with 2923 took around 15 seconds to load on my Galaxy S8. My PI is at some so I can't test it before 8PM CEST.
I guess the less processing power, the longer the loading times. My desktop PC loaded them instantly.

**Comment by Birdroun** [comment]
For comparaison before I was using https://github.com/balbuze/volumio-plugins/tree/master/plugins/music_service/volspotconnect2 which is using vollibrespot 0.1.6 and I had no trouble loading 3k playlists with spotify connect. Sure no big trouble ! It's more a tiny fix that can help some people, there is no that much 3k playlists !

**Comment by SirWindfield** [comment]
Even if it is spotifyd specific, we use a library called rspotify, so we might need to fix it on their part.
I'll take a look at it today in the evening and will give you a report once I did some testing :)

**Comment by Birdroun** [comment]
Well, I got a small spotify update just now on desktop and now everything is working flawlessly !
So I'm going to say that it's fixed for the moment, thank you though !
