### ISSUE TITLE
can connect from computer but not from phone

### ISSUE THREAD

**Issue by indiscible** [Spotifyd/spotifyd#266]
I have spotifyd running on a raspberrypi.
It is visible from my computer and my phone.
When I connect from my computer it works flawlessly, but when I connect from  my phone the demons just dies.
Maybe it's a spotify issue because I just realized i can actually listen to two different songs on my phone and computer.

**Comment by albansch** [comment]
> Maybe it's a spotify issue because I just realized i can actually listen to two different songs on my phone and computer.
Interesting, I have exactly the same issue using Spotify client within Linux: since yeterday, cannot connect to it with Spotify Connect, and I'm also able to stream 2 different songs at the same time on a phone and a windows computer. In my case, I'm not yet using spotifyd... Wonder what's going on.

**Comment by SirWindfield** [comment]
Is this fixed? Really sounds like a problem on spotify's side.

**Comment by SirWindfield** [comment]
I'll close the issue for now. Feel free to open it if you still encounter the issue.
