### ISSUE TITLE
Provide brew formula

### ISSUE THREAD

**Issue by SirWindfield** [Spotifyd/spotifyd#311]
[Brew](https://brew.sh) is the de-facto standard package manager on macOS. It would be beneficial to provide a formula for `spotifyd`. Since formulae allow custom builds using parameters, it would be possible to provide useful configurations like `--with-pulseaudio`, `--with-portaudio`, `--with-keyring` and `--with-dbus-mpris` as well as some meta options that combine multiple together.

It might be worth looking into a custom Github Action that updates the formula using the new pre-built binary hashes, bumps the version with the latest tag and pushes a PR to the `brew cask` repository.

**Comment by Yarn** [comment]
I took a first pass at making a brew formula. It uses a release from my repo since that's what actually builds for me. I'm not really sure what to do for the test. The formula does work.

https://gist.github.com/Yarn/6322faec65c7a5480954d33650a1962b

I probably won't work on this more, at least for a while, since release builds take a really long time to build on my laptop and the 1GB for brew to have its own rust install is rough when I'm starting with 110GB isn't great either.

That said, if you have something to put for the test and make a new release I'll finish up other stuff for submitting it to homebrew-core. If you don't have an idea for a test I can submit it without one and see what they say.

**Comment by samuela** [comment]
Another option is to use the repo as its own tap, and then have the formula just download binaries. My understanding is that the core homebrew people like to have everything compiled from scratch, but nothing prevents you from doing whatever you'd like in custom taps.

**Comment by Lykegenes** [comment]
I created a Homebrew tap that installs Spotifyd from the generated binaries if anyone is interested!
#561 

I wanted to add it directly to Homebrew-core, but they only accept formulas that are compiled from the source. I have no experience with Rust, so I simply used the binaries.
