### ISSUE TITLE
[DBUS] Missing Volume dbus property

### ISSUE THREAD

**Issue by zack6849** [Spotifyd/spotifyd#397]
Hi!

I noticed you're missing the Volume property (and that's the only one that's missing that I saw)

One of the programs I use relies on that, I wrote up a quick shim to implement it and just return 0, and that worked

However, i was wondering about implementing the actual player volume

I did some poking around and found this:
https://github.com/ramsayleung/rspotify/blob/master/src/spotify/model/device.rs#L12

So it does seem that the volume /should/ be accessible from the context of a current playback context, I don't know rust well enough to implement it, I gave it a shot and got this, but it failed and returned 0 consistently.

I also think it should be f64, not u32, but was just trying to keep the type consistent with what rspotify used

I've attached a patch for what I tried.
[0001-DBUS-Failed-attempt-at-implementing-volume-property.patch.txt](https://github.com/Spotifyd/spotifyd/files/3744856/0001-DBUS-Failed-attempt-at-implementing-volume-property.patch.txt)

Thanks!

**Comment by SirWindfield** [comment]
Thanks for reporting this!

**Comment by zack6849** [comment]
Just curious, is this going to be implemented?

**Comment by SirWindfield** [comment]
I hope someone can step in and help me out on it. I do not have a lot of time right now (exams , ye 🥳). I am open for PRs though (always!). There are currently a bunch of unmerged ones but those are relatively big and I just don't have the time right now to skim over them in detail.

We are waiting mostly for a librespot merge to continue active, regular development. But dbus issues can be fixed in the meantime nonetheless :p

**Comment by slondr** [comment]
Implemented by #697
