### ISSUE TITLE
error: Could not compile `whoami`

### ISSUE THREAD

**Issue by klee1001** [Spotifyd/spotifyd#416]
**Description**
The compiling process exit with the following error messages:
error: Could not compile `whoami`

error[E0599]: no function or associated item named `uninit` found for type `std::mem::MaybeUninit<[u8; 256]>` in the current scope
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/whoami-0.5.3/src/unix.rs:157:53
    |
157 |     let mut string = mem::MaybeUninit::<[u8; 256]>::uninit();
    |                      -------------------------------^^^^^^
    |                      |
    |                      function or associated item not found in `std::mem::MaybeUninit<[u8; 256]>`

**To Reproduce**
cargo build --release --no-default-features --features alsa_backend,dbus_keyring,dbus_mpris

**Comment by SirWindfield** [comment]
Hey!

First off, there is a reason why I added the version section within the template :) Please make sure to include everything that is applicable for your issue in there (which is definitely the version). I also added a section for logs. Make sure to use those templates. It makes my life easier and results in faster and better responds for you.

You are using an outdated version of Rust, probably because you run Ubuntu. Make sure to install Rust using https://rustup.rs. Also, uninstall using `sudo apt-get uninstall rust` before you install the new version.

**Comment by SirWindfield** [comment]
Closing for now. Feel free to re-open if you still encounter this issue.
