### ISSUE TITLE
Is offline playback possible?

### ISSUE THREAD

**Issue by steinerlein** [Spotifyd/spotifyd#493]
Please excuse the misuse of the issue tracker. I am looking for a way to build a client that can (temporarily) save marked playlists for offline playback like the official clients do.
Is this possible with this daemon/librespot?
Thanks!

**Comment by SirWindfield** [comment]
This is against the ToS of Spotify itself.

**Comment by randompersondude** [comment]
> This is against the ToS of Spotify itself.

sorry, I've just came across this now, and don't the official spotify clients allow you to save songs offline?

**Comment by eladyn** [comment]
Even apart from ToS issues, this feature wouldn't really make sense in `spotifyd` IMO, since `spotifyd` requires a controlling application to do anything sensible which in turn requires an active network connection. Caching is already happening such that content isn't unnecessarily downloaded multiple times.
So I'm not sure how you'd expect offline playback to work?
