### ISSUE TITLE
"volume_normalisation = true" set the volume lower than it should be.

### ISSUE THREAD

**Issue by mrhieu059** [Spotifyd/spotifyd#583]
I'm installing spotifyd on both of my laptop (MBP - OSX] and Thinkpad - Linux) and using the example config on this git and its set `volume_normalisation = true` `normalisation_pregain = -10` as default. However this lower the volume which I could barely listen to it (on my thinkpad) and on MBP it lower about 70% of the total volume. First I thought this was some kind of incorrect device and mixer argument so I decided to install spotify on both of my laptop with different audio_backend (portaudio, alsa and pulseaudio). But it didn't raise the volume a bit, so I attempted to set `volume_normalisation` to ` false` and surprisingly the volume was improve (now the volume is the same volume as I listen to spotify via a web browser).
I don't know if it's a bug or not, can someone explain it?

**Comment by SirWindfield** [comment]
Volue normalization is a feature that normalizes the volume of all songs you listen to, e.g. increases/decreases the dB to let us believe they are all at the same volume level. You can probably adjust the pregain (instead of -10 try 10 or something else) that should normalise it into louder dB space. It is normal behaviour and not a bug though.

Desktop clients allow normalization as well. Those do normalize to lower pregains as well. I think the -10 is actually spotify's default value on those clients. If you check your phone/desktop and enable/disable the feature, you'll notice that it gets quiter as well.
