### ISSUE TITLE
Move readme content to (well structured) wiki

### ISSUE THREAD

**Issue by SirWindfield** [Spotifyd/spotifyd#635]
Just skimmed through the readme and it is really cluttered with a lot of information. The TOC helps but I think a lot of the stuff can be moved over to the wiki. We should keep just the important part inside the readme (like getting started and contributions etc.)

I will probably create empty wiki pages the coming days to showcase the idea that I have. Any help is appreciated in this department, as usual :)

**Comment by vringar** [comment]
Hey,
A project I currently work on tried using the wiki and failed, which is why I would advise against using the wiki.
The situation boils down to two things:
- It's not part of the repository
- It's either write all or people with write access to project

This results in the following problems:
- The wiki and the repository and the wiki can easily get out of date, as a grep of the repo doesn't show the wiki
- There is no PR process for wiki pages
- If the wiki is writeable by everybody with an account they can get spammed/defaced by bots quite easily

My suggestion would be to have a docs/wiki folder in the project root and to everything in there.

Would you accept a PR that adds such a folder with the structure you outlined in the wiki?

**Comment by SirWindfield** [comment]
Fair criticism on your part. I do admit, it would make more sense that way. The only things I'd like to keep in the readme are the installation process through provided binaries, from source should go there. contributions, license, common issues, credits. Configuration should be in the wiki as well, as it is super long. Just a link to the right file shoud be enough.

I didn't create any wiki structure yet. I dodnt have the time. Feel free to structre them as you'd like and I will review the PR and request changes as well as do them myself once a draft is up and running.

Some higher abstracted topics would be configuration, compilation, features (audio backends). The next step would be to merge the wiki and the docs folder. But that can be done in another PR.

**Comment by SirWindfield** [comment]
I'll assign you for now to the issue so there aren't two people working on it :)

**Comment by vringar** [comment]
Oh god, I completely forgot about this. Sorry.
I might just get around to starting something on this Monday.

**Comment by SirWindfield** [comment]
Don't worry about it! don't feel forced to do it just because you are assigned to it :) If you still want to do help out though, I won't say no ;) We will probably use [mdbook](https://github.com/rust-lang/mdBook). The content will then have to be inside a folder (`docs`). If you don't want to get the tool to know, you can just split the content into separate files and I will then convert them over to a markdown book :)

**Comment by vringar** [comment]
I really want to contribute back to this project because I use it extensively.
I've always wanted to get into mdbook, so I'll try to format it appropriately and create a draft PR with my progress. :)
I might even take a stab at publishing the mdbook to gh-pages using GitHub Actions.
