### ISSUE TITLE
Config from the readme causes a panic

### ISSUE THREAD

**Issue by noir-Z** [Spotifyd/spotifyd#698]
version 0.2.24

Putting my credentials in quotes, as per the readme, will make spotifyd panic.
Without quotes it authenticates.

Because it might be relevant:
my username starts with a ".", the password has no special characters
```
username = ".****" 
password = "****"
```
when I put this in the config, authentication will fail.

**Comment by myrkvi** [comment]
This happens with other config options as well.

```toml
[global]
username = "******"
password = "******"
backend = "pulseaudio"
device_name = "HelloWorld"
```
In this example, all the values are interpreted with the quotes surrounding them, which in addition to passing an incorrect username and password, will also make spotifyd panic when trying to set the backend, as it is interpreting the value as `"pulseaudio"` instead of `pulseaudio`.

Additional note:
The [README](https://github.com/Spotifyd/spotifyd#configuration-file) specifies that the configuration format is TOML, but [TOML](https://toml.io/en/v0.5.0#string) does not allow unquoted strings.

**Comment by robinvd** [comment]
@myrkvi We recently moved to TOML, so the current readme says TOML, but if you didnt compile from the master branch then it does not use TOML yet.

i have made an issue for a new release: https://github.com/Spotifyd/spotifyd/issues/702

https://github.com/Spotifyd/spotifyd/issues/701 seems to be somewhat the same issue

**Comment by slondr** [comment]
With the new release, can this, #701, and #712 all be closed?

**Comment by JojiiOfficial** [comment]
Yeah I'd say so. In case some of those issues still persists, we can always reopen them or create new issues.

**Comment by slondr** [comment]
Sounds good, I'll get to it
