### ISSUE TITLE
aarch64-linux-gnu-ld.gold: -Wl,--as-needed: unknown option

### ISSUE THREAD

**Issue by ghost** [Spotifyd/spotifyd#89]
Trying to cross-compile to aarch64, basically everything works, however, the final step fails:

```
  = note: aarch64-linux-gnu-ld.gold: -Wl,--as-needed: unknown option
          aarch64-linux-gnu-ld.gold: use the --help option for usage information

error: aborting due to previous error
error: Could not compile `spotifyd`.
```
 Used command is `cargo build --release --target aarch64-unknown-linux-gnu`

Cargo config: 

```
[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-ld.gold"
ar="aarch64-linux-gnu-ar"
```

Somebody can explain me what I'm doing wrong?
Thanks...

**Comment by praul** [comment]
I was able to cross compile with
KG_CONFIG_PATH=/usr/lib/aarch64-unknown-linux-gnu/pkgconfig PKG_CONFIG_ALLOW_CROSS=1 cargo build --target=aarch64-unknown-linux-gnu --release

**Comment by archi** [comment]
For me, the only problem was that cargo would be using the systems "cc" as linker.
Creating a `~/.cargo/config` with content

```
[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"
```

created a working aarch64 binary.

For the rest, I followed the wiki, but used arm64 instead of armhf:
https://github.com/Spotifyd/spotifyd/wiki/Cross-Compiling-on-Ubuntu

(Be careful with the `sources.list` change: Somehow a bunch of `> ` were added during copy/paste, resulting in an empty `sources.list`).
