### ISSUE TITLE
keeps skipping when playing a song | unable to load decryption key 

### ISSUE THREAD

**Issue by byteme-git** [Spotifyd/spotifyd#907]
**Description**

Spotifyd Daemon starts normally and logs in successfully. The config file is read and the created Device shows up in spotify-tui and the official Spotify app on a different (mobile) device. When i start a song on the device created by spotifyd however, it just keeps skipping though the songs and not playing. The behaviour is the same whether i start it via the official app or spotify-tui.

The important error that keeps it from working seems to be "error audio key 0 2" and "Unable to load decryption key"

Steaming on the phone works as expected.

**To Reproduce**
1. Start daemon 
2. let it log in via config file
3. start a song on the spotifyd-created device
4. watch it all go bannanas

**Expected behavior**
Spotifyd playing the selected Song

**Logs**
<details><summary>Click to show logs</summary>

**Log when started (shows it does correctly authenticate)**

Mär 02 20:41:36 LinuxLaptop01 systemd[488465]: Started A spotify playing daemon.
Mär 02 20:41:36 LinuxLaptop01 spotifyd[521317]: Loading config from "/home/user01/.config/spotifyd/spotifyd.conf"
Mär 02 20:41:36 LinuxLaptop01 spotifyd[521317]: No proxy specified
Mär 02 20:41:36 LinuxLaptop01 spotifyd[521317]: Using software volume controller.
Mär 02 20:41:36 LinuxLaptop01 spotifyd[521317]: Connecting to AP "gew1-accesspoint-e-nzpk.ap.spotify.com:443"
Mär 02 20:41:36 LinuxLaptop01 spotifyd[521317]: Authenticated as "[removed]" !
Mär 02 20:41:36 LinuxLaptop01 spotifyd[521317]: Country: "DE"

**Log when trying to start a song**

Mär 02 20:42:48 LinuxLaptop01 spotifyd[521317]: Loading <Atmen> with Spotify URI <spotify:track:0U56ojZsNfX2KoVKOtPhiZ>
Mär 02 20:42:48 LinuxLaptop01 spotifyd[521317]: error audio key 0 2
Mär 02 20:42:48 LinuxLaptop01 spotifyd[521317]: Unable to load decryption key
Mär 02 20:42:48 LinuxLaptop01 spotifyd[521317]: Unable to load <SpotifyId { id: 39505691577244741253602179970634215893, audio_type: Track }>
Mär 02 20:42:48 LinuxLaptop01 spotifyd[521317]: Skipping to next track
Mär 02 20:42:48 LinuxLaptop01 spotifyd[521317]: Loading <2015> with Spotify URI <spotify:track:01WFilfIcivzOBTDbzxpXp>
Mär 02 20:42:48 LinuxLaptop01 spotifyd[521317]: error audio key 0 2
Mär 02 20:42:48 LinuxLaptop01 spotifyd[521317]: Unable to load decryption key
Mär 02 20:42:48 LinuxLaptop01 spotifyd[521317]: Unable to load <SpotifyId { id: 1370967755279187051962917586466992079, audio_type: Track }>
Mär 02 20:42:48 LinuxLaptop01 spotifyd[521317]: Skipping to next track

</details>

**Compilation flags** 
Using spotifyd-full-git from the AUR

**Versions (please complete the following information):**

- OS: Manjaro Linux x86_64  5.10.18-1-MANJARO 
- Spotifyd: 0.3.0.123.g1032694-1 
- cargo: 1:1.50.0-1
- backend: pulseaudio 14.2-2
- Desktop Enviroment: plasma-desktop 5.21.1-1

 **Additional context**
using AppArmour as an MAC
using UFW as a firewall

**Comment by Fuzzypyro** [comment]
I am also experiencing this exact same behavior. However I am not getting the same described issues in my logs. I tried between both AUR then official. It used to work perfectly fine until after I updated to 0.3.0. I swapped out the config file for the new file already. My logs however don't specify an issue with the decryption key as labeled above.

<details>
 <summary>Output run as no-daemon</summary>

Loading config from "/home/michael/.config/spotifyd/spotifyd.conf"
No proxy specified
Using alsa volume controller.
ALSA lib control.c:1471:(snd_ctl_open_noupdate) Invalid CTL alsa_audio_device
Couldn't read volume from alsa device with name "alsa_audio_device".
Caught panic with message: called `Result::unwrap()` on an `Err` value: Io(Os { code: 98, kind: AddrInUse, message: "Address already in use" })
</details>

<details>
  <summary>Journalctl logs</summary>
  
Oct 09 05:41:49 Luna-Go spotifyd[1281]: Loading config from "/home/michael/.config/spotifyd/spotifyd.conf"
Oct 09 05:41:49 Luna-Go spotifyd[1281]: No proxy specified
Oct 09 05:41:49 Luna-Go spotifyd[1281]: Using alsa volume controller.
Oct 09 05:41:50 Luna-Go spotifyd[1281]: Couldn't read volume from alsa device with name "default".
Oct 09 05:41:50 Luna-Go spotifyd[1281]: Caught panic with message: called `Result::unwrap()` on an `Err` value: Os { code: 19, kind: Other, message: "No such device" }
Oct 09 05:42:03 Luna-Go spotifyd[1689]: Loading config from "/home/michael/.config/spotifyd/spotifyd.conf"
Oct 09 05:42:03 Luna-Go spotifyd[1689]: No proxy specified
Oct 09 05:42:03 Luna-Go spotifyd[1689]: Using alsa volume controller.
Oct 09 05:42:03 Luna-Go spotifyd[1689]: Couldn't read volume from alsa device with name "default".
Oct 09 05:42:03 Luna-Go spotifyd[1689]: Connecting to AP "guc3-accesspoint-b-jfjt.ap.spotify.com:443"
Oct 09 05:42:04 Luna-Go spotifyd[1689]: Authenticated as "226wyt3rwnp52ynvmhrffsc7a" !
Oct 09 05:42:04 Luna-Go spotifyd[1689]: Couldn't read volume from alsa device with name "default".
Oct 09 05:42:04 Luna-Go spotifyd[1689]: Couldn't set volume: "Couldn\'t find selem with name \'PCM\'."
Oct 09 05:42:04 Luna-Go spotifyd[1689]: Country: "US"
Oct 09 05:42:04 Luna-Go spotifyd[1689]: Unhandled DBus message: (Signal, Some("/org/freedesktop/DBus"), Some("org.freedesktop.DBus"), Some("NameAcquired"))
Oct 09 05:42:04 Luna-Go spotifyd[1689]: Unhandled DBus message: (Signal, Some("/org/freedesktop/DBus"), Some("org.freedesktop.DBus"), Some("NameAcquired"))
Oct 09 05:42:04 Luna-Go spotifyd[1689]: Couldn't fetch metadata from spotify: Ok(None)
Oct 09 05:42:06 Luna-Go spotifyd[1689]: Couldn't fetch metadata from spotify: Ok(None)
Oct 09 05:46:25 Luna-Go spotifyd[1689]: Caught panic with message: called `Result::unwrap()` on an `Err` value: Error(Hyper(Error(Connect, Custom { kind: Other, error: "failed to lookup address information: Temporary failure in n>
Oct 09 05:46:37 Luna-Go spotifyd[3037]: Loading config from "/home/michael/.config/spotifyd/spotifyd.conf"
Oct 09 05:46:37 Luna-Go spotifyd[3037]: No proxy specified
Oct 09 05:46:37 Luna-Go spotifyd[3037]: Using alsa volume controller.
Oct 09 05:46:37 Luna-Go spotifyd[3037]: Couldn't read volume from alsa device with name "default".
Oct 09 05:46:37 Luna-Go spotifyd[3037]: Connecting to AP "guc3-accesspoint-c-fb6k.ap.spotify.com:443"
Oct 09 05:46:38 Luna-Go spotifyd[3037]: Authenticated as "226wyt3rwnp52ynvmhrffsc7a" !
Oct 09 05:46:38 Luna-Go spotifyd[3037]: Couldn't read volume from alsa device with name "default".
Oct 09 05:46:38 Luna-Go spotifyd[3037]: Couldn't set volume: "Couldn\'t find selem with name \'PCM\'."
Oct 09 05:46:38 Luna-Go spotifyd[3037]: Country: "US"
Oct 09 05:46:38 Luna-Go spotifyd[3037]: Unhandled DBus message: (Signal, Some("/org/freedesktop/DBus"), Some("org.freedesktop.DBus"), Some("NameAcquired"))
Oct 09 05:46:38 Luna-Go spotifyd[3037]: Unhandled DBus message: (Signal, Some("/org/freedesktop/DBus"), Some("org.freedesktop.DBus"), Some("NameAcquired"))
Oct 09 05:46:38 Luna-Go spotifyd[3037]: Couldn't fetch metadata from spotify: Ok(None)
Oct 09 05:46:39 Luna-Go spotifyd[3037]: Couldn't fetch metadata from spotify: Ok(None)
Oct 09 05:46:39 Luna-Go spotifyd[3037]: Couldn't fetch metadata from spotify: Ok(None)
Oct 09 06:45:17 Luna-Go spotifyd[3037]: Unhandled DBus message: (Signal, Some("/org/freedesktop/DBus"), Some("org.freedesktop.DBus"), Some("NameAcquired"))
Oct 09 06:45:17 Luna-Go spotifyd[3037]: Unhandled DBus message: (Signal, Some("/org/freedesktop/DBus"), Some("org.freedesktop.DBus"), Some("NameAcquired"))
Oct 09 06:45:18 Luna-Go spotifyd[3037]: Couldn't fetch metadata from spotify: Ok(None)
Oct 09 06:45:18 Luna-Go spotifyd[3037]: Couldn't fetch metadata from spotify: Ok(None)
Oct 09 06:45:18 Luna-Go spotifyd[3037]: Couldn't fetch metadata from spotify: Ok(None)
Oct 09 07:48:33 Luna-Go spotifyd[3037]: Unhandled DBus message: (Signal, Some("/org/freedesktop/DBus"), Some("org.freedesktop.DBus"), Some("NameAcquired"))
Oct 09 07:48:33 Luna-Go spotifyd[3037]: Unhandled DBus message: (Signal, Some("/org/freedesktop/DBus"), Some("org.freedesktop.DBus"), Some("NameAcquired"))
Oct 09 07:48:33 Luna-Go spotifyd[3037]: Couldn't fetch metadata from spotify: Ok(None)
Oct 09 07:48:33 Luna-Go spotifyd[3037]: Couldn't fetch metadata from spotify: Ok(None)
Oct 09 07:48:34 Luna-Go spotifyd[3037]: Couldn't fetch metadata from spotify: Ok(None)
Oct 09 17:43:19 Luna-Go spotifyd[3037]: Unhandled DBus message: (Signal, Some("/org/freedesktop/DBus"), Some("org.freedesktop.DBus"), Some("NameAcquired"))
Oct 09 17:43:19 Luna-Go spotifyd[3037]: Unhandled DBus message: (Signal, Some("/org/freedesktop/DBus"), Some("org.freedesktop.DBus"), Some("NameAcquired"))
Oct 09 21:45:10 Luna-Go spotifyd[3037]: Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }
-- Boot 1f5b814d39ba4641991c398e57c278d1 --
Oct 20 04:13:05 Luna-Go spotifyd[979]: Loading config from "/home/michael/.config/spotifyd/spotifyd.conf"
Oct 20 04:13:05 Luna-Go spotifyd[979]: No proxy specified
Oct 20 04:13:05 Luna-Go spotifyd[979]: Using alsa volume controller.
Oct 20 04:13:06 Luna-Go spotifyd[979]: Couldn't read volume from alsa device with name "default".
Oct 20 04:13:06 Luna-Go spotifyd[979]: Caught panic with message: called `Result::unwrap()` on an `Err` value: Os { code: 19, kind: Other, message: "No such device" }
</details>

**I actually just fixed it for myself. I Commented out the line** 

**device = alsa_audio_device #omit for macOS**

It turns out the backend pulse-audio doesn't support the selection device. The song skipping comes from where it is searching for a device to play the selected music but it just skips because there is no selected device. Not sure if this helps you but hopefully this might help someone experiencing what I did since this is where I ended up. 

**Compilation flags**
Using official arch repos

**Versions**

- OS: aarch64 Linux 5.11.1-1-MANJARO-ARM
- Spotifyd: 0.3.0
- Cargo: 1.50.0
- Backend: pulseaudio 14.2

**Comment by byteme-git** [comment]
I don't have an audio device configured, so it does not seem to be the same issue but i'll do some more digging and maybe your experience will help. Glad u you could fix ur issue though. 

Other situations with the same behavior would be interesting, maybe it'll help narrow it down.

**Comment by robinvd** [comment]
@byteme-git could you paste your config (without auth)?

**Comment by byteme-git** [comment]
Sure:
<details><summary>Show config (stored in ~/.config/spotifyd/spotifyd.conf)</summary>

[global]
username = "[...]"
password = "[...]"
backend = "pulseaudio"
device_name = "Laptop"
bitrate = 160
cache_path = /home/user01/.cache/spotifyd
no_audio_cache = true
initial_volume = "90"
volume_normalisation = true
normalisation_pregain = -10
device_type = "computer"

</details>
