### ISSUE TITLE
Tracking issue for upgrading librespot to v0.2.0

### ISSUE THREAD

**Issue by JojiiOfficial** [Spotifyd/spotifyd#969]
As mentioned in #717 here the tracking issue for upgrading librespot to v0.2.0

closes #717 #945

**Comment by capnfabs** [comment]
Hey! I started work on this a few weeks ago for a hobby project ([video](https://capnfabs.net/posts/why-is-this-floppy-disk-drive-clicking-incessantly/ill-communication.mp4)); the upgrade work is by no means complete yet, but wanted to link it here in case it's helpful to someone as a reference for a cleaner PR. 

Current status: it works, but:
- it panic whenever you try to quit with Ctrl+C (this is probably easy to fix, I just haven't done it yet)
- dbus is a bit complicated. The dbus libraries changed significantly as part of supporting tokio 1.0, which is required for librespot v0.2.0. I'd wanted to rework the current dbus_mpris implementation anyway -- would be nice to support property change signals, and to not hit the Spotify API on every dbus property fetch -- so I've been doing it in the same branch so that I can use `dbus_crossroads`, which seems to be the "newer" way of implementing a DBUS server.
- I've ignored automated tests so far.


Code is here: https://github.com/Spotifyd/spotifyd/compare/master...capnfabs:fabian/wip-big-upgrade

Would you be open to reworking DBUS and doing the upgrade in the same PR? I would _normally_ try and do the minimal possible upgrade in a PR, but am very much _not_ doing this in the code on that branch.

**Comment by capnfabs** [comment]
Cleaned up that branch a bit, fixed the Ctrl+C issue, and pushed it to https://github.com/Spotifyd/spotifyd/pull/977
