### ISSUE TITLE
can't get spotifyd working

### ISSUE THREAD

**Issue by ceceba223** [Spotifyd/spotifyd#972]
I tried setting up Spotify TUI and Spotifyd. Spotify TUI is working fine, but i can't get Spotifyd working.
I followed the [docs](https://spotifyd.github.io/spotifyd/installation/Ubuntu.html) to compile spotifyd but when i run `./target/release/spotifyd` nothing happens, it shows up neither as a device in Spotify TUI, nor as a process in htop. 
 Did i do something wrong during the installation? Is there a way I can install Spotifyd without needing to compile it first?

**Comment by ceceba223** [comment]
I also tried making the spotifyd file an executable by running:
`sudo chmod +x ./target/release/spotifyd`

**Comment by deadlysyn** [comment]
fwiw i've had similar problems...still trying to find the right path. followed the docs to build from scratch (since available packages either didn't have options i need, or didn't appear to work with keyring which i'm trying to fix). have a functional rust env on my machine (built a few other things) but `cargo build --release --no-default-features --features pulseaudio_backend,dbus_keyring,dbus_mpris` results in a binary which reports NOT to support pulseaudio (only alsa available) or keyring. all the required libs are installed.

**Comment by ceceba223** [comment]
I got it working! I think what finally solved it was putting the spotifyd binary into `~/.cargo/bin/`
