### ISSUE TITLE
command to execute on start and stop of playlist / queue

### ISSUE THREAD

**Issue by vacy** [Spotifyd/spotifyd#980]
**Is your feature request related to a problem? Please describe.**
energy saving

**Describe the solution you'd like**
My Speaker got a webinterface, events like start and stop of playlist/queue shall run each a separate command.
I would have a small program to be called that goes to the speakers API to power on, change source, change volume and turn of on playlist/queue stop.
Please dont implement "one" commandparameter for start 'and' stop, but each one command.

**Describe alternatives you've considered**
its a manual process

**Comment by eladyn** [comment]
This should already be possible using `on_song_change_hook` (configurable via config file or cli: `--on_song_change_hook`).

To run separate commands on `start` or `stop` you can write a simple shell script like the following (not tested)
```bash
#!/bin/bash

case "$PLAYER_EVENT" in
  start)
    echo "playback started" ;;
  stop)
    echo "placback stopped" ;;
  pause)
    echo "playback paused" ;;
esac
```

And of course instead of those `echo`s, insert the commands you want to execute. For details on what events and env variables are available, see [here](https://github.com/Spotifyd/spotifyd/blob/d6b1ea515c7a0315a0809d5e80d4c900180738cf/src/process.rs#L47-L147).

Hope this helps!
