### ISSUE TITLE
Playing music offline

### ISSUE THREAD

**Issue by mustaphazorgati** [Spotifyd/spotifyd#987]
**Is your feature request related to a problem? Please describe.**
I don't always have an internet connection. Thus I can't play my music everywhere

**Describe the solution you'd like**
An offline mode like the official spotify client where you can pre-download songs and albums and play them back whenever you're on the go. E.g. in the subway or in the train.

**Describe alternatives you've considered**
Any solution, even some hacky ones on my side, where I can play music offline is fine :)

Is this enough context, or do you need any more details? :sweat_smile:
I am not sure if this is even possible using spotifyd, but asking doesn't cost anthing :wink:

**Comment by harrisonthorne** [comment]
iirc this is against Spotify's terms of use for their API. Would be a nice feature to have, though

**Comment by bevsxyz** [comment]
Can the cache feature be repurposed for offline support?

**Comment by harrisonthorne** [comment]
silly bot.

I'd like to hear the devs' personal opinions on bevsxyz's comment before this issue is closed

**Comment by JojiiOfficial** [comment]
@harrisonthorne 
> iirc this is against Spotify's terms of use for their API

Yes it is against the TOS of Spotify, so is spotifyd.

I think since this is not a spotify player in particular but a daemon, it requires internet to be controlled anyway (afaik). "Abusing" the caching feature `could` work (at least for not having to download the audio) but not without forking and changing librespot. Also there is other data which is required to be cached, like artist, playlist and song information. I'm not a dev of spotifyd but I doubt this becoming a feature in spotifyd, regardless of someone willing it to do or not.

**Comment by eladyn** [comment]
> I think since this is not a spotify player in particular but a daemon, it requires internet to be controlled anyway (afaik).

I would say so, too. `spotifyd` is a headless application that needs a client to function, which in turn requires an active internet connection. See also [this issue](https://github.com/librespot-org/librespot/issues/152) why this isn't done on the `librespot` side, this applies as well to `spotifyd`. (What *could* be improved is `spotifyd`s resilience to spotty internet connections and intermediate connection losses, but that is not what this issue is about.)
